version: "3.9"
services:
  backend:
    build: ./backend
  frontend:
    build: ./frontend
  nginx:
    image: nginx
    volumes:
    - ./nginx-templates:/etc/nginx/templates
    ports:
    - 8080:80
    environment:
    - NGINX_PORT=80
    - PHONYX_BACKEND=backend:3000
    - PHONYX_FRONTEND=frontend:80